General:
  Label: "My fit"

Samples:
  - Name: "Data"
    Tree: "pseudodata"
    Path: "ntuples/data.root"
    Color: "#000000"

  - Name: "Signal"
    Tree: "signal"
    Path: "ntuples/prediction.root"
    Color: "#FFAA55"

  - Name: "Background"
    Tree: "background"
    Path: "ntuples/prediction.root"
    Color: "#F55EE33"

Regions:
  - Name: "Signal Region"
    Variable: "jet_pt"
    Binning: [0, 150, 300]

Systematics:
  - Name: Luminosity
    OverallDown: -0.02
    OverallUp: 0.02
    Samples: all
    Type: OVERALL

NormFactors:
  - Name: "Signal strength"
    Nominal: 1
    Min: 0
    Max: 5
    Samples: Signal
