General:
  Label: "My fit"

Samples:
  - Name: "Data"
    Path: "ntuples/pseudodata.root"
    Color: "#000000"

  - Name: "Signal"
    Path: "ntuples/prediction.root"
    Color: "#FFAA55"

  - Name: "Background"
    Path: "ntuples/prediction.root"
    Color: "#F55EE33"

Regions:
  - Name: "Signal region"
    Variable: "jet_pt"
    AutoBin:
      Type: "TransfoD"
      Param_1: 4
      Param_2: 4

  - Name: "Control Region"
    Variable: "el_pt"
    Binning: [0, 150, 300]

Systematics:
  - Name: Luminosity
    OverallDown: -0.02
    OverallUp: 0.02
    Samples: all
    Type: OVERALL

NormFactors:
  - Name: "Signal strength"
    Nominal: 1
    Min: 0
    Max: 5
    Samples: Signal
